server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://aivle12team-mariadb.czqb4x9zq3oq.ap-northeast-2.rds.amazonaws.com:3306/aivle12_mariadb?allowMultiQueries=true&characterEncoding=UTF-8
    username: aivle12
    password: 12345678
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 테이블이 없으면 자동으로 만들어주는 옵션
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
jwt:
  secret: your-256-bit-secret-key-change-this-in-production-min-32-characters
  expiration: 7200000
